// ── Export presets ───────────────────────────────────────────────────────────
//
// Named configurations for common use cases. Each preset sets processing
// options to sensible defaults. Users can apply a preset and then override
// individual settings.

export const PRESETS = [
  {
    id: 'deposition',
    name: 'Deposition',
    desc: 'Court deposition — clean speech, balanced speakers',
    settings: {
      mode: 'stereo',
      format: 'mp3',
      rate: '48000',
      normalize: true,
      trim: true,
      fade: true,
      fadeDur: 0.3,
      hpf: true,
      denoise: true,
      denoiseQuality: 'best',
      autoLevel: true,
      declip: false,
      enhance: false,
      dereverb: false,
    },
  },
  {
    id: 'phone',
    name: 'Phone Recording',
    desc: 'Phone call or dial-in — enhance clarity and remove noise',
    settings: {
      mode: 'stereo',
      format: 'mp3',
      rate: '48000',
      normalize: true,
      trim: true,
      fade: false,
      fadeDur: 0.5,
      hpf: true,
      denoise: true,
      denoiseQuality: 'best',
      autoLevel: false,
      declip: false,
      enhance: true,
      dereverb: false,
    },
  },
  {
    id: 'courtroom',
    name: 'Courtroom',
    desc: 'Large room recording — reduce echo and background noise',
    settings: {
      mode: 'split',
      format: 'wav',
      rate: '48000',
      normalize: true,
      trim: false,
      fade: false,
      fadeDur: 0.5,
      hpf: true,
      denoise: true,
      denoiseQuality: 'fast',
      autoLevel: true,
      declip: false,
      enhance: false,
      dereverb: true,
    },
  },
  {
    id: 'archive',
    name: 'Archive',
    desc: 'Lossless archival — preserve original quality, minimal processing',
    settings: {
      mode: 'keep',
      format: 'flac',
      rate: '48000',
      normalize: false,
      trim: false,
      fade: false,
      fadeDur: 0.5,
      hpf: false,
      denoise: false,
      denoiseQuality: 'fast',
      autoLevel: false,
      declip: false,
      enhance: false,
      dereverb: false,
    },
  },
  {
    id: 'quick',
    name: 'Quick Share',
    desc: 'Small file for email — voice-optimized Opus, fast denoise',
    settings: {
      mode: 'stereo',
      format: 'opus',
      rate: '48000',
      normalize: true,
      trim: true,
      fade: true,
      fadeDur: 0.3,
      hpf: true,
      denoise: true,
      denoiseQuality: 'fast',
      autoLevel: false,
      declip: false,
      enhance: false,
      dereverb: false,
    },
  },
]
